<?php

/**
 * @file
 * Main token_view_filter module file.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_build().
 */
function token_views_filter_views_pre_build(ViewExecutable $view) {
  $token = \Drupal::token();
  if ($view->filter) {
    foreach ($view->filter as &$filter) {
      if (!empty($filter->options['use_tokens'])) {
        // Replace tokens,
        $filter->value = $token->replace($filter->value);
      }
    }
  }
}

